INSERT INTO time (nome) VALUES
                            ('Flamengo'),
                            ('Palmeiras'),
                            ('Corinthians'),
                            ('São Paulo'),
                            ('Santos'),
                            ('Grêmio'),
                            ('Internacional'),
                            ('Atlético Mineiro'),
                            ('Cruzeiro'),
                            ('Fluminense');
INSERT INTO jogador (nome, nascimento, genero, altura, time_id) VALUES
                                                                    ('Gabriel Barbosa', '1996-08-30', 'Masculino', 1.76, 1),
                                                                    ('Bruno Henrique', '1990-12-30', 'Masculino', 1.84, 1),
                                                                    ('Gustavo Scarpa', '1994-01-05', 'Masculino', 1.82, 2),
                                                                    ('Raphael Veiga', '1995-06-19', 'Masculino', 1.76, 2),
                                                                    ('Cássio', '1987-06-06', 'Masculino', 1.96, 3),
                                                                    ('Roger Guedes', '1996-10-02', 'Masculino', 1.82, 3),
                                                                    ('Luciano', '1993-05-24', 'Masculino', 1.80, 4),
                                                                    ('Calleri', '1993-10-14', 'Masculino', 1.86, 4),
                                                                    ('Marcos Leonardo', '2003-05-02', 'Masculino', 1.75, 5),
                                                                    ('Lucas Braga', '1996-03-05', 'Masculino', 1.78, 5),
                                                                    ('Suárez', '1987-01-24', 'Masculino', 1.82, 6),
                                                                    ('Ferreira', '1999-03-15', 'Masculino', 1.85, 6),
                                                                    ('Wanderson', '1994-10-07', 'Masculino', 1.75, 7),
                                                                    ('Alan Patrick', '1991-05-13', 'Masculino', 1.72, 7),
                                                                    ('Hulk', '1986-07-25', 'Masculino', 1.80, 8),
                                                                    ('Paulinho', '2000-07-15', 'Masculino', 1.77, 8),
                                                                    ('Gilberto', '1993-03-07', 'Masculino', 1.86, 9),
                                                                    ('Wesley', '2000-03-13', 'Masculino', 1.85, 9),
                                                                    ('German Cano', '1988-02-02', 'Masculino', 1.80, 10),
                                                                    ('André', '2001-07-16', 'Masculino', 1.76, 10);
INSERT INTO estadio (nome, endereco, time_id) VALUES
                                                  ('Maracanã', 'Rio de Janeiro - RJ', 1),
                                                  ('Allianz Parque', 'São Paulo - SP', 2),
                                                  ('Neo Química Arena', 'São Paulo - SP', 3),
                                                  ('Morumbi', 'São Paulo - SP', 4),
                                                  ('Vila Belmiro', 'Santos - SP', 5),
                                                  ('Arena do Grêmio', 'Porto Alegre - RS', 6),
                                                  ('Beira-Rio', 'Porto Alegre - RS', 7),
                                                  ('Arena MRV', 'Belo Horizonte - MG', 8),
                                                  ('Mineirão', 'Belo Horizonte - MG', 9),
                                                  ('Maracanã', 'Rio de Janeiro - RJ', 10);
INSERT INTO campeonato (ano, nome) VALUES
                                       (2023, 'Brasileirão Série A'),
                                       (2023, 'Copa do Brasil'),
                                       (2024, 'Brasileirão Série A'),
                                       (2024, 'Copa do Brasil'),
                                       (2023, 'Libertadores');
INSERT INTO campeonato_time (campeonato_id, time_id) VALUES
                                                         (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10),
                                                         (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10),
                                                         (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10),
                                                         (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10),
                                                         (5, 1), (5, 2), (5, 3), (5, 4), (5, 6), (5, 7), (5, 8);
INSERT INTO partida (dataPartida, campeonato_id, timeMandante_id, timeVisitante_id, golsMandante, golsVisitante) VALUES
                                                                                                                     ('2023-05-10', 1, 1, 2, 2, 1),
                                                                                                                     ('2023-05-15', 1, 3, 4, 1, 1),
                                                                                                                     ('2023-05-20', 1, 5, 6, 0, 2),
                                                                                                                     ('2023-06-05', 2, 2, 3, 3, 0),
                                                                                                                     ('2023-06-10', 2, 4, 5, 2, 2),
                                                                                                                     ('2023-06-15', 2, 6, 7, 1, 1),
                                                                                                                     ('2023-07-01', 5, 1, 6, 4, 2),
                                                                                                                     ('2023-07-08', 5, 2, 7, 1, 0),
                                                                                                                     ('2024-04-05', 3, 8, 9, 2, 1),
                                                                                                                     ('2024-04-12', 3, 10, 1, 0, 3),
                                                                                                                     ('2024-04-20', 4, 3, 5, 1, 0),
                                                                                                                     ('2024-04-27', 4, 4, 6, 2, 2),
                                                                                                                     ('2024-05-05', 5, 3, 8, 1, 1),
                                                                                                                     ('2024-05-12', 5, 4, 7, 0, 2);